networks:
  app-network:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - vue
      - express
  vue:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - ./app/package.json:/app/package.json
    networks:
      - app-network
    working_dir: /app
    command: sh -c "npm install && npm run serve"
  express:
    image: node:latest
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
      - ./server/package.json:/server/package.json
    networks:
      - app-network
    working_dir: /server
    command: sh -c "npm install && npm run serve"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network